<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.baomibing</groupId>
  <artifactId>snapper-dependence</artifactId>
  <version>${revision}</version>
  <packaging>pom</packaging>

  <name>snapper-dependence</name>
  <url>https://gitee.com/ifrog/snapper-dependence.git</url>
  <description>Common spring boot cloud configuration</description>

  <licenses>
    <license>
      <name>The Apache License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>

  <developers>
    <developer>
      <id>snapper-dependence</id>
      <name>zening</name>
      <email>316279828@qq.com</email>
    </developer>
  </developers>

  <properties>
    <revision>3.2.4</revision>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <java.version>1.8</java.version>
    <maven-assembly-plugin.version>3.3.0</maven-assembly-plugin.version>
    <maven-dependency-plugin.version>3.1.2</maven-dependency-plugin.version>
    <maven-jar-plugin.version>3.2.0</maven-jar-plugin.version>
    <maven-compiler-plugin.version>3.8.1</maven-compiler-plugin.version>
    <maven-surefire-plugin.version>3.0.0-M5</maven-surefire-plugin.version>
    <maven-resources-plugin.version>3.2.0</maven-resources-plugin.version>
    <maven-javadoc-plugin.version>3.2.0</maven-javadoc-plugin.version>
    <maven-source-plugin.version>3.2.1</maven-source-plugin.version>
    <maven-clean-plugin.version>3.1.0</maven-clean-plugin.version>
    <maven-install-plugin.version>3.0.0-M1</maven-install-plugin.version>
    <maven-release-plugin.version>3.0.0-M1</maven-release-plugin.version>
    <maven-deploy-plugin.version>3.0.0-M1</maven-deploy-plugin.version>
    <maven-war-plugin.version>3.3.1</maven-war-plugin.version>
    <maven-release-plugin.version>3.0.0-M1</maven-release-plugin.version>
    <maven.staging.plugin>1.6.7</maven.staging.plugin>
    <maven-shade-plugin.version>3.5.0</maven-shade-plugin.version>
    <maven.gpg.pluign>1.5</maven.gpg.pluign>
    <maven.flatten.plugin>1.1.0</maven.flatten.plugin>
    <maven.central-publishing.plugin>0.4.0</maven.central-publishing.plugin>

    <alibaba.cloud.version>2021.0.5.0</alibaba.cloud.version>
    <antisamy.version>1.5.7</antisamy.version>
    <asm.version>9.2</asm.version>
    <auto-service.version>1.1.0</auto-service.version>

    <bitwalker.version>1.21</bitwalker.version>
    <bucket4j.version>7.6.0</bucket4j.version>

    <caffeine.version>2.9.3</caffeine.version>
    <commons-fileupload.version>1.5</commons-fileupload.version>
    <commons-beanutils.version>1.9.4</commons-beanutils.version>
    <commons-exec.version>1.3</commons-exec.version>
    <commons.collections4.version>4.4</commons.collections4.version>
    <commons-lang3.version>3.10</commons-lang3.version>
    <commons-io.version>2.11.0</commons-io.version>
    <commons-pool2.version>2.8.0</commons-pool2.version>
    <commons-text.version>1.9</commons-text.version>
    <commons-codec.version>1.15</commons-codec.version>
    <cors-filter.version>2.10</cors-filter.version>

    <diff-match.version>1.2</diff-match.version>
    <druid.version>1.2.15</druid.version>
    <druid-starter.version>1.1.22</druid-starter.version>
    <dynamic.datasource.version>3.6.1</dynamic.datasource.version>
    <dozer.version>6.5.2</dozer.version>

    <easy-captcha.version>1.6.2</easy-captcha.version>
    <easy-random.version>5.0.0</easy-random.version>
    <easy-rule.version>4.1.1</easy-rule.version>
    <exp4j.version>0.4.8</exp4j.version>

    <fastdfs-client-java.version>1.27.0</fastdfs-client-java.version>
    <fastjson.version>1.2.83</fastjson.version>
    <!--		<feign-form.version>3.8.0</feign-form.version>-->
    <freemarker.version>2.3.29</freemarker.version>

    <groovy-all.version>4.0.26</groovy-all.version>
    <guava.version>33.0.0-jre</guava.version>

    <hibernate.validator.version>6.0.21.Final</hibernate.validator.version>
    <httpmime.version>4.5.13</httpmime.version>
    <httpclient.version>4.5.13</httpclient.version>
    <httpasyncclient.version>4.1.4</httpasyncclient.version>
    <httpcore.version>4.4.13</httpcore.version>
    <hutool.version>5.8.24</hutool.version>

    <icu4j.version>73.1</icu4j.version>
    <ip2region.version>2.7.0</ip2region.version>
    <ipaddress.version>5.4.0</ipaddress.version>

    <jackson.version>2.15.0</jackson.version>
    <jansi.version>2.4.0</jansi.version>
    <javassist.version>3.29.2-GA</javassist.version>
    <javax-mail.version>1.6.2</javax-mail.version>
    <jasypt.version>3.0.3</jasypt.version>
    <jetcache.version>2.6.0</jetcache.version>
    <joda-time.version>2.12.5</joda-time.version>
    <jodd-mail.version>5.1.5</jodd-mail.version>
    <jjwt.version>0.11.5</jjwt.version>
    <jsqlparser.version>4.6</jsqlparser.version>
    <JustAuth.version>1.13.2</JustAuth.version>
    <jsoup.version>1.11.3</jsoup.version>

    <knife4j.version>2.0.3</knife4j.version>

    <lmax.disruptor.version>3.4.2</lmax.disruptor.version>
    <logger.version>2.2.6.RELEASE</logger.version>
    <logback.version>1.2.12</logback.version>
    <lombok.version>1.18.12</lombok.version>

    <mail.version>1.6.1</mail.version>
    <mica.auto.version>1.1.0</mica.auto.version>
    <mybatis-plus-starter.version>3.4.0</mybatis-plus-starter.version>
    <mybatis-spring.version>2.0.3</mybatis-spring.version>
    <mybatis-typehandlers.version>1.0.2</mybatis-typehandlers.version>
    <mysql-connector.version>8.0.33</mysql-connector.version>

    <nacos.version>2.2.1.RELEASE</nacos.version>
    <nimbus.version>9.31</nimbus.version>
    <netty-socketio.version>1.7.18</netty-socketio.version>

    <objenesis.version>2.6</objenesis.version>
    <org.slf4j.version>1.7.22</org.slf4j.version>

    <p6spy.version>3.9.1</p6spy.version>
    <pinyin4j.version>2.5.1</pinyin4j.version>
    <poi.version>4.1.2</poi.version>
    <proguard.plugin.version>2.3.1</proguard.plugin.version>
    <proguard.version>6.2.2</proguard.version>

    <reflections.version>0.10.2</reflections.version>

    <search-mybatis-plus.version>1.0.6-plus_3_4-SNAPSHOT</search-mybatis-plus.version>
    <security-oauth2.version>2.5.0.RELEASE</security-oauth2.version>
    <security-jwt.version>1.1.1.RELEASE</security-jwt.version>

    <shiro.version>1.11.0</shiro.version>
    <smart-doc.version>2.0.9</smart-doc.version>
    <snakeyaml.version>1.33</snakeyaml.version>

    <spring.boot.version>2.6.15</spring.boot.version>
    <spring.cloud.version>2021.0.9</spring.cloud.version>
    <spring.security.version>2.2.5.RELEASE</spring.security.version>

    <transmittable-thread-local.version>2.14.2</transmittable-thread-local.version>

    <undertow-core.version>2.2.24.Final</undertow-core.version>

    <vavr.version>0.10.4</vavr.version>


  </properties>

  <build>
    <finalName>${project.name}</finalName>
    <!--配置资源文件过滤，如果有其他需要打包的资源，需要重载此配置节 -->
    <directory>target</directory>
    <outputDirectory>target/classes</outputDirectory>
    <testOutputDirectory>target/test-classes</testOutputDirectory>
    <!--		<sourceDirectory>src/main/java</sourceDirectory>-->
    <!--		<testSourceDirectory>src/test/java</testSourceDirectory>-->
    <resources>
      <resource>
        <directory>src/main/java</directory>
        <filtering>false</filtering>
        <excludes>
          <exclude>**/*.java</exclude>
        </excludes>
      </resource>
      <resource>
        <directory>${basedir}/src/main/resources</directory>
        <filtering>true</filtering>
        <includes>
          <include>**/*</include>
        </includes>
      </resource>
    </resources>
    <testResources>
      <testResource>
        <directory>src/test/resources</directory>
        <filtering>false</filtering>
      </testResource>
    </testResources>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>flatten-maven-plugin</artifactId>
          <version>${maven.flatten.plugin}</version>
          <configuration>
            <updatePomFile>true</updatePomFile>
            <flattenMode>resolveCiFriendliesOnly</flattenMode>
          </configuration>
          <executions>
            <execution>
              <id>flatten</id>
              <phase>process-resources</phase>
              <goals>
                <goal>flatten</goal>
              </goals>
            </execution>
            <execution>
              <id>flatten.clean</id>
              <phase>clean</phase>
              <goals>
                <goal>clean</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-jar-plugin</artifactId>
          <version>${maven-jar-plugin.version}</version>
          <configuration>
            <archive>
              <index>true</index>
              <manifest>
                <addClasspath>true</addClasspath>

                <addDefaultImplementationEntries/>
                <addDefaultSpecificationEntries/>
                <addBuildEnvironmentEntries/>

              </manifest>
              <manifestEntries>
                <Implementation-Title>${project.name}</Implementation-Title>
                <Implementation-Version>${project.version}</Implementation-Version>
                <url>${project.url}</url>
              </manifestEntries>

            </archive>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-maven-plugin</artifactId>
          <version>${spring.boot.version}</version>
          <configuration>
            <finalName>${project.build.finalName}</finalName>
          </configuration>
          <executions>
            <execution>
              <goals>
                <goal>repackage</goal>
              </goals>
            </execution>
          </executions>
        </plugin>

        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-resources-plugin</artifactId>
          <version>${maven-resources-plugin.version}</version>
          <configuration>
            <useDefaultDelimiters>true</useDefaultDelimiters>
            <encoding>UTF-8</encoding>
          </configuration>
        </plugin>

        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>${maven-compiler-plugin.version}</version>
          <configuration>
            <source>${java.version}</source>
            <target>${java.version}</target>
            <encoding>UTF-8</encoding>
            <compilerArgs>
              <arg>-parameters</arg>
            </compilerArgs>
          </configuration>
        </plugin>

        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-dependency-plugin</artifactId>
          <version>${maven-dependency-plugin.version}</version>
          <executions>
            <execution>
              <phase>package</phase>
              <goals>
                <goal>copy-dependencies</goal>
              </goals>
              <configuration>
                <outputDirectory>${project.build.directory}/lib</outputDirectory>
              </configuration>
            </execution>
          </executions>
        </plugin>

        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-assembly-plugin</artifactId>
          <version>${maven-assembly-plugin.version}</version>
        </plugin>

        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-shade-plugin</artifactId>
          <version>${maven-shade-plugin.version}</version>
        </plugin>

        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>${maven-deploy-plugin.version}</version>
          <configuration>
            <skip>true</skip>
          </configuration>
        </plugin>

        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-release-plugin</artifactId>
          <version>${maven-release-plugin.version}</version>
          <configuration>
            <autoVersionSubmodules>true</autoVersionSubmodules>
          </configuration>
        </plugin>

        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-gpg-plugin</artifactId>
          <version>${maven.gpg.pluign}</version>
          <executions>
            <execution>
              <id>sign-artifacts</id>
              <phase>verify</phase>
              <goals>
                <goal>sign</goal>
              </goals>
            </execution>
          </executions>
        </plugin>

      </plugins>
    </pluginManagement>

    <plugins>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
      </plugin>

      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>flatten-maven-plugin</artifactId>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-deploy-plugin</artifactId>
        <configuration>
          <skip>false</skip>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <dependencyManagement>
    <dependencies>

      <dependency>
        <groupId>com.baomibing</groupId>
        <artifactId>snapper-tool</artifactId>
        <version>${project.version}</version>
      </dependency>

      <dependency>
        <groupId>com.baomibing</groupId>
        <artifactId>snapper-email</artifactId>
        <version>${project.version}</version>
      </dependency>

      <dependency>
        <groupId>com.baomibing</groupId>
        <artifactId>snapper-core-starter</artifactId>
        <version>${project.version}</version>
      </dependency>

      <dependency>
        <groupId>com.baomibing</groupId>
        <artifactId>snapper-cache-starter</artifactId>
        <version>${project.version}</version>
      </dependency>

      <dependency>
        <groupId>com.baomibing</groupId>
        <artifactId>snapper-web-starter</artifactId>
        <version>${project.version}</version>
      </dependency>

      <dependency>
        <groupId>com.baomibing</groupId>
        <artifactId>snapper-log-starter</artifactId>
        <version>${project.version}</version>
      </dependency>

      <dependency>
        <groupId>com.baomibing</groupId>
        <artifactId>snapper-feign-starter</artifactId>
        <version>${project.version}</version>
      </dependency>


      <dependency>
        <groupId>com.baomibing</groupId>
        <artifactId>snapper-orm-starter</artifactId>
        <version>${project.version}</version>
      </dependency>


      <dependency>
        <groupId>com.baomibing</groupId>
        <artifactId>snapper-authority-starter</artifactId>
        <version>${project.version}</version>
      </dependency>


      <dependency>
        <groupId>com.baomibing</groupId>
        <artifactId>snapper-security-micro</artifactId>
        <version>${project.version}</version>
      </dependency>


      <dependency>
        <groupId>com.baomibing</groupId>
        <artifactId>snapper-security-standalone</artifactId>
        <version>${project.version}</version>
      </dependency>


      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>${spring.boot.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>${spring.cloud.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

      <dependency>
        <groupId>com.alibaba.cloud</groupId>
        <artifactId>spring-cloud-alibaba-dependencies</artifactId>
        <version>${alibaba.cloud.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-security</artifactId>
        <version>${spring.security.version}</version>
      </dependency>

      <dependency>
        <groupId>org.lionsoul</groupId>
        <artifactId>ip2region</artifactId>
        <version>${ip2region.version}</version>
      </dependency>

      <dependency>
        <groupId>eu.bitwalker</groupId>
        <artifactId>UserAgentUtils</artifactId>
        <version>${bitwalker.version}</version>
      </dependency>

      <!-- Sql解析 -->
      <dependency>
        <groupId>com.github.jsqlparser</groupId>
        <artifactId>jsqlparser</artifactId>
        <version>${jsqlparser.version}</version>
      </dependency>

      <!-- 持久层相关 -->
      <dependency>
        <groupId>com.github.ulisesbocchio</groupId>
        <artifactId>jasypt-spring-boot</artifactId>
        <version>${jasypt.version}</version>
      </dependency>

      <dependency>
        <groupId>com.alibaba</groupId>
        <artifactId>druid-spring-boot-starter</artifactId>
        <version>${druid.version}</version>
      </dependency>
      <dependency>
        <groupId>p6spy</groupId>
        <artifactId>p6spy</artifactId>
        <version>${p6spy.version}</version>
      </dependency>

      <dependency>
        <groupId>com.alicp.jetcache</groupId>
        <artifactId>jetcache-starter-redis-lettuce</artifactId>
        <version>${jetcache.version}</version>
      </dependency>

      <dependency>
        <groupId>net.arccode</groupId>
        <artifactId>fastdfs-client-java</artifactId>
        <version>${fastdfs-client-java.version}</version>
      </dependency>

      <!-- 对象转换 -->
      <dependency>
        <groupId>com.github.dozermapper</groupId>
        <artifactId>dozer-spring-boot-starter</artifactId>
        <version>${dozer.version}</version>
      </dependency>

      <dependency>
        <groupId>com.github.dozermapper</groupId>
        <artifactId>dozer-core</artifactId>
        <version>${dozer.version}</version>
      </dependency>

      <dependency>
        <groupId>com.github.dozermapper</groupId>
        <artifactId>dozer-spring4</artifactId>
        <version>${dozer.version}</version>
      </dependency>

      <dependency>
        <groupId>io.jsonwebtoken</groupId>
        <artifactId>jjwt-api</artifactId>
        <version>${jjwt.version}</version>
      </dependency>

      <dependency>
        <groupId>org.ow2.asm</groupId>
        <artifactId>asm</artifactId>
        <version>${asm.version}</version>
      </dependency>

      <dependency>
        <groupId>com.github.ben-manes.caffeine</groupId>
        <artifactId>caffeine</artifactId>
        <version>${caffeine.version}</version>
      </dependency>

      <dependency>
        <groupId>commons-beanutils</groupId>
        <artifactId>commons-beanutils</artifactId>
        <version>${commons-beanutils.version}</version>
      </dependency>

      <dependency>
        <groupId>commons-io</groupId>
        <artifactId>commons-io</artifactId>
        <version>${commons-io.version}</version>
      </dependency>

      <dependency>
        <groupId>org.apache.commons</groupId>
        <artifactId>commons-lang3</artifactId>
        <version>${commons-lang3.version}</version>
      </dependency>

      <dependency>
        <groupId>com.fasterxml.jackson</groupId>
        <artifactId>jackson-bom</artifactId>
        <version>${jackson.version}</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>

      <dependency>
        <groupId>org.javassist</groupId>
        <artifactId>javassist</artifactId>
        <version>${javassist.version}</version>
      </dependency>
      <dependency>
        <groupId>org.objenesis</groupId>
        <artifactId>objenesis</artifactId>
        <version>${objenesis.version}</version>
      </dependency>


      <dependency>
        <groupId>cn.hutool</groupId>
        <artifactId>hutool-all</artifactId>
        <version>${hutool.version}</version>
      </dependency>

      <dependency>
        <groupId>com.alibaba</groupId>
        <artifactId>fastjson</artifactId>
        <version>${fastjson.version}</version>
      </dependency>

      <dependency>
        <groupId>com.alibaba</groupId>
        <artifactId>transmittable-thread-local</artifactId>
        <version>${transmittable-thread-local.version}</version>
      </dependency>

      <dependency>
        <groupId>com.google.guava</groupId>
        <artifactId>guava</artifactId>
        <version>${guava.version}</version>
      </dependency>

      <!-- commons-exec -->
      <dependency>
        <groupId>org.apache.commons</groupId>
        <artifactId>commons-exec</artifactId>
        <version>${commons-exec.version}</version>
      </dependency>


      <!-- commons-collections4 -->
      <dependency>
        <groupId>org.apache.commons</groupId>
        <artifactId>commons-collections4</artifactId>
        <version>${commons.collections4.version}</version>
      </dependency>


      <dependency>
        <groupId>commons-codec</groupId>
        <artifactId>commons-codec</artifactId>
        <version>${commons-codec.version}</version>
      </dependency>

      <dependency>
        <groupId>org.apache.commons</groupId>
        <artifactId>commons-pool2</artifactId>
        <version>${commons-pool2.version}</version>
      </dependency>

      <dependency>
        <groupId>org.jodd</groupId>
        <artifactId>jodd-mail</artifactId>
        <version>${jodd-mail.version}</version>
      </dependency>

      <dependency>
        <groupId>org.bitbucket.cowwoc</groupId>
        <artifactId>diff-match-patch</artifactId>
        <version>${diff-match.version}</version>
      </dependency>

      <dependency>
        <groupId>org.apache.httpcomponents</groupId>
        <artifactId>httpclient</artifactId>
        <version>${httpclient.version}</version>
      </dependency>

      <dependency>
        <groupId>org.apache.httpcomponents</groupId>
        <artifactId>httpcore</artifactId>
        <version>${httpcore.version}</version>
      </dependency>

      <dependency>
        <groupId>org.apache.httpcomponents</groupId>
        <artifactId>httpmime</artifactId>
        <version>${httpmime.version}</version>
      </dependency>

      <dependency>
        <groupId>org.apache.httpcomponents</groupId>
        <artifactId>httpcore-nio</artifactId>
        <version>${httpcore.version}</version>
      </dependency>

      <dependency>
        <groupId>org.apache.httpcomponents</groupId>
        <artifactId>httpasyncclient</artifactId>
        <version>${httpasyncclient.version}</version>
      </dependency>

      <dependency>
        <groupId>org.freemarker</groupId>
        <artifactId>freemarker</artifactId>
        <version>${freemarker.version}</version>
      </dependency>

      <dependency>
        <groupId>com.lmax</groupId>
        <artifactId>disruptor</artifactId>
        <version>${lmax.disruptor.version}</version>
      </dependency>

      <dependency>
        <groupId>org.projectlombok</groupId>
        <artifactId>lombok</artifactId>
        <version>${lombok.version}</version>
      </dependency>

      <!-- 拼音转化-汉字转拼音 -->
      <dependency>
        <groupId>com.belerweb</groupId>
        <artifactId>pinyin4j</artifactId>
        <version>${pinyin4j.version}</version>
      </dependency>


      <!-- 阿拉伯数字转英文大写 -->
      <dependency>
        <groupId>com.ibm.icu</groupId>
        <artifactId>icu4j</artifactId>
        <version>${icu4j.version}</version>
      </dependency>

      <!-- 时间日期操作包 -->
      <dependency>
        <groupId>joda-time</groupId>
        <artifactId>joda-time</artifactId>
        <version>${joda-time.version}</version>
      </dependency>

      <!-- CROS相关 -->
      <dependency>
        <groupId>com.thetransactioncompany</groupId>
        <artifactId>cors-filter</artifactId>
        <version>${cors-filter.version}</version>
      </dependency>

      <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-api</artifactId>
        <version>${org.slf4j.version}</version>
      </dependency>
      <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>jcl-over-slf4j</artifactId>
        <version>${org.slf4j.version}</version>
      </dependency>

      <!-- logback日志 -->

      <dependency>
        <groupId>ch.qos.logback</groupId>
        <artifactId>logback-access</artifactId>
        <version>${logback.version}</version>
      </dependency>

      <dependency>
        <groupId>ch.qos.logback</groupId>
        <artifactId>logback-classic</artifactId>
        <version>${logback.version}</version>
      </dependency>

      <dependency>
        <groupId>ch.qos.logback</groupId>
        <artifactId>logback-core</artifactId>
        <version>${logback.version}</version>
      </dependency>

      <dependency>
        <groupId>com.github.vladimir-bukhtoyarov</groupId>
        <artifactId>bucket4j-core</artifactId>
        <version>${bucket4j.version}</version>
      </dependency>

      <dependency>
        <groupId>commons-fileupload</groupId>
        <artifactId>commons-fileupload</artifactId>
        <version>${commons-fileupload.version}</version>
      </dependency>

      <dependency>
        <groupId>org.yaml</groupId>
        <artifactId>snakeyaml</artifactId>
        <version>${snakeyaml.version}</version>
      </dependency>

      <dependency>
        <groupId>mysql</groupId>
        <artifactId>mysql-connector-java</artifactId>
        <version>${mysql-connector.version}</version>
      </dependency>


      <dependency>
        <groupId>org.mybatis</groupId>
        <artifactId>mybatis-typehandlers-jsr310</artifactId>
        <version>${mybatis-typehandlers.version}</version>
      </dependency>

      <dependency>
        <groupId>org.springframework.security</groupId>
        <artifactId>spring-security-jwt</artifactId>
        <version>${security-jwt.version}</version>
      </dependency>

      <dependency>
        <groupId>org.springframework.security.oauth</groupId>
        <artifactId>spring-security-oauth2</artifactId>
        <version>${security-oauth2.version}</version>
      </dependency>


      <dependency>
        <groupId>com.nimbusds</groupId>
        <artifactId>nimbus-jose-jwt</artifactId>
        <version>${nimbus.version}</version>
      </dependency>

      <dependency>
        <groupId>org.hibernate.validator</groupId>
        <artifactId>hibernate-validator</artifactId>
        <version>${hibernate.validator.version}</version>
      </dependency>

      <dependency>
        <groupId>com.corundumstudio.socketio</groupId>
        <artifactId>netty-socketio</artifactId>
        <version>${netty-socketio.version}</version>
      </dependency>

      <dependency>
        <groupId>io.vavr</groupId>
        <artifactId>vavr</artifactId>
        <version>${vavr.version}</version>
      </dependency>

      <dependency>
        <groupId>com.baomidou</groupId>
        <artifactId>mybatis-plus-boot-starter</artifactId>
        <version>${mybatis-plus-starter.version}</version>
      </dependency>

      <!--			<dependency>-->
      <!--				<groupId>com.baomibing</groupId>-->
      <!--				<artifactId>search-mybatis-plus</artifactId>-->
      <!--				<version>${search-mybatis-plus.version}</version>-->
      <!--			</dependency>-->

      <dependency>
        <groupId>com.github.seancfoley</groupId>
        <artifactId>ipaddress</artifactId>
        <version>${ipaddress.version}</version>
      </dependency>

      <dependency>
        <groupId>io.undertow</groupId>
        <artifactId>undertow-core</artifactId>
        <version>${undertow-core.version}</version>
      </dependency>

      <dependency>
        <groupId>com.sun.mail</groupId>
        <artifactId>javax.mail</artifactId>
        <version>${javax-mail.version}</version>
      </dependency>

      <dependency>
        <groupId>org.fusesource.jansi</groupId>
        <artifactId>jansi</artifactId>
        <version>${jansi.version}</version>
      </dependency>

      <dependency>
        <groupId>com.google.auto.service</groupId>
        <artifactId>auto-service</artifactId>
        <version>${auto-service.version}</version>
      </dependency>

      <dependency>
        <groupId>org.reflections</groupId>
        <artifactId>reflections</artifactId>
        <version>${reflections.version}</version>
      </dependency>

      <dependency>
        <groupId>org.apache.shiro</groupId>
        <artifactId>shiro-spring</artifactId>
        <version>${shiro.version}</version>
        <exclusions>
          <exclusion>
            <artifactId>slf4j-api</artifactId>
            <groupId>org.slf4j</groupId>
          </exclusion>
        </exclusions>
      </dependency>

      <dependency>
        <groupId>net.objecthunter</groupId>
        <artifactId>exp4j</artifactId>
        <version>${exp4j.version}</version>
      </dependency>


      <dependency>
        <groupId>org.apache.groovy</groupId>
        <artifactId>groovy-all</artifactId>
        <version>${groovy-all.version}</version>
        <type>pom</type>
      </dependency>


    </dependencies>
  </dependencyManagement>

  <repositories>
    <repository>
      <id>aliyun-repos</id>
      <url>https://maven.aliyun.com/nexus/content/groups/public/</url>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
    <repository>
      <id>spring-milestones</id>
      <name>Spring Milestones</name>
      <url>https://repo.spring.io/libs-milestone</url>
    </repository>
  </repositories>

  <pluginRepositories>
    <pluginRepository>
      <id>aliyun-plugin</id>
      <url>https://maven.aliyun.com/nexus/content/groups/public/</url>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </pluginRepository>
  </pluginRepositories>


  <modules>
    <module>snapper-authority-starter</module>
    <module>snapper-cache-starter</module>
    <module>snapper-core-starter</module>
    <module>snapper-email</module>
    <module>snapper-feign-starter</module>
    <module>snapper-gateway-starter</module>
    <module>snapper-log-starter</module>
    <module>snapper-tool</module>
    <module>snapper-orm-starter</module>
    <module>snapper-web-starter</module>
    <module>snapper-security-micro</module>
    <module>snapper-security-standalone</module>
    <module>snapper-business-starter</module>
  </modules>


</project>
